# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: camera_params.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'camera_params.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63\x61mera_params.proto\"D\n\x13V3ReqSetCameraParam\x12\x10\n\x08param_id\x18\x01 \x01(\x03\x12\x0c\n\x04\x66lag\x18\x02 \x01(\x05\x12\r\n\x05value\x18\x03 \x01(\x05\"E\n\x14V3ReqSetExposureGain\x12\x10\n\x08param_id\x18\x01 \x01(\x03\x12\x0c\n\x04\x66lag\x18\x02 \x01(\x05\x12\r\n\x05value\x18\x03 \x01(\x05\"3\n\x10V3ReqAdjustParam\x12\x10\n\x08param_id\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\x05\"D\n\x12V3ReqStreamControl\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\x05\x12\x0e\n\x06\x66ield2\x18\x02 \x01(\x05\x12\x0e\n\x06\x66ield3\x18\x03 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'camera_params_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_V3REQSETCAMERAPARAM']._serialized_start=23
  _globals['_V3REQSETCAMERAPARAM']._serialized_end=91
  _globals['_V3REQSETEXPOSUREGAIN']._serialized_start=93
  _globals['_V3REQSETEXPOSUREGAIN']._serialized_end=162
  _globals['_V3REQADJUSTPARAM']._serialized_start=164
  _globals['_V3REQADJUSTPARAM']._serialized_end=215
  _globals['_V3REQSTREAMCONTROL']._serialized_start=217
  _globals['_V3REQSTREAMCONTROL']._serialized_end=285
# @@protoc_insertion_point(module_scope)
