# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: device_config.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'device_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64\x65vice_config.proto\"%\n\x0eV3ReqModeQuery\x12\x13\n\x0btarget_mode\x18\x01 \x01(\x05\",\n\x0eV3ResModeQuery\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0c\n\x04mode\x18\x02 \x01(\x05\"*\n\x17V3ReqShootingModeSwitch\x12\x0f\n\x07mode_id\x18\x01 \x01(\x05\"8\n\x17V3ResShootingModeSwitch\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07mode_id\x18\x02 \x01(\x05\"T\n\x0fV3ReqModeSwitch\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\x05\x12\x0e\n\x06\x66ield2\x18\x02 \x01(\x05\x12!\n\x05inner\x18\x03 \x01(\x0b\x32\x12.V3ModeSwitchInner\"\"\n\x11V3ModeSwitchInner\x12\r\n\x05value\x18\x01 \x01(\x05\"-\n\x0fV3ResModeSwitch\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0c\n\x04mode\x18\x02 \x01(\x05\"\x16\n\x14V3ReqGetDeviceConfig\"9\n\x14V3ResGetDeviceConfig\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x13\n\x0b\x63onfig_data\x18\x02 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'device_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_V3REQMODEQUERY']._serialized_start=23
  _globals['_V3REQMODEQUERY']._serialized_end=60
  _globals['_V3RESMODEQUERY']._serialized_start=62
  _globals['_V3RESMODEQUERY']._serialized_end=106
  _globals['_V3REQSHOOTINGMODESWITCH']._serialized_start=108
  _globals['_V3REQSHOOTINGMODESWITCH']._serialized_end=150
  _globals['_V3RESSHOOTINGMODESWITCH']._serialized_start=152
  _globals['_V3RESSHOOTINGMODESWITCH']._serialized_end=208
  _globals['_V3REQMODESWITCH']._serialized_start=210
  _globals['_V3REQMODESWITCH']._serialized_end=294
  _globals['_V3MODESWITCHINNER']._serialized_start=296
  _globals['_V3MODESWITCHINNER']._serialized_end=330
  _globals['_V3RESMODESWITCH']._serialized_start=332
  _globals['_V3RESMODESWITCH']._serialized_end=377
  _globals['_V3REQGETDEVICECONFIG']._serialized_start=379
  _globals['_V3REQGETDEVICECONFIG']._serialized_end=401
  _globals['_V3RESGETDEVICECONFIG']._serialized_start=403
  _globals['_V3RESGETDEVICECONFIG']._serialized_end=460
# @@protoc_insertion_point(module_scope)
