# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notify.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'notify.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cnotify.proto\"P\n\x15\x41stroCalibrationState\x12\x1a\n\x05state\x18\x01 \x01(\x0e\x32\x0b.AstroState\x12\x1b\n\x13plate_solving_times\x18\x02 \x01(\x05\"-\n\x11\x43\x61librationResult\x12\x0b\n\x03\x61zi\x18\x01 \x01(\x01\x12\x0b\n\x03\x61lt\x18\x02 \x01(\x01\"<\n\x1aResNotifyOneClickGotoState\x12\x1e\n\x05state\x18\x01 \x01(\x0e\x32\x0f.OperationState*\x82\x01\n\x0eOperationState\x12\x18\n\x14OPERATION_STATE_IDLE\x10\x00\x12\x1b\n\x17OPERATION_STATE_RUNNING\x10\x01\x12\x1c\n\x18OPERATION_STATE_STOPPING\x10\x02\x12\x1b\n\x17OPERATION_STATE_STOPPED\x10\x03*\x8d\x01\n\nAstroState\x12\x14\n\x10\x41STRO_STATE_IDLE\x10\x00\x12\x17\n\x13\x41STRO_STATE_RUNNING\x10\x01\x12\x18\n\x14\x41STRO_STATE_STOPPING\x10\x02\x12\x17\n\x13\x41STRO_STATE_STOPPED\x10\x03\x12\x1d\n\x19\x41STRO_STATE_PLATE_SOLVING\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notify_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPERATIONSTATE']._serialized_start=208
  _globals['_OPERATIONSTATE']._serialized_end=338
  _globals['_ASTROSTATE']._serialized_start=341
  _globals['_ASTROSTATE']._serialized_end=482
  _globals['_ASTROCALIBRATIONSTATE']._serialized_start=16
  _globals['_ASTROCALIBRATIONSTATE']._serialized_end=96
  _globals['_CALIBRATIONRESULT']._serialized_start=98
  _globals['_CALIBRATIONRESULT']._serialized_end=143
  _globals['_RESNOTIFYONECLICKGOTOSTATE']._serialized_start=145
  _globals['_RESNOTIFYONECLICKGOTOSTATE']._serialized_end=205
# @@protoc_insertion_point(module_scope)
