# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v3_astro.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'v3_astro.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ev3_astro.proto\"%\n\x15V3ReqSaveStackedImage\x12\x0c\n\x04path\x18\x01 \x01(\t\"3\n\x15V3ResSaveStackedImage\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0c\n\x04path\x18\x02 \x01(\t\"\x16\n\x14V3ReqListSavedImages\"T\n\x12V3ReqStatusPolling\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\x05\x12\x0e\n\x06\x66ield2\x18\x02 \x01(\x05\x12\x0e\n\x06\x66ield3\x18\x03 \x01(\x05\x12\x0e\n\x06\x66ield4\x18\x04 \x01(\x05\"#\n\x13V3ReqGetAstroParams\x12\x0c\n\x04mode\x18\x01 \x01(\x05\"G\n\x13V3ResGetAstroParams\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\"\n\x06params\x18\x02 \x03(\x0b\x32\x12.V3AstroParamsData\"t\n\x11V3AstroParamsData\x12\x10\n\x08\x65xposure\x18\x01 \x01(\t\x12\x0c\n\x04gain\x18\x02 \x01(\x05\x12\r\n\x05total\x18\x03 \x01(\x05\x12\r\n\x05\x63ount\x18\x04 \x01(\x05\x12\x13\n\x0bpipe_params\x18\x06 \x01(\tJ\x04\x08\x05\x10\x06R\x06\x66ormat\"%\n\x13V3ReqSetAstroParams\x12\x0e\n\x06params\x18\x01 \x01(\t\"8\n\x13V3ResSetAstroParams\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x13\n\x0bpipe_params\x18\x02 \x01(\t\"X\n\x17V3ReqGetExposurePresets\x12\x1d\n\x05query\x18\x01 \x01(\x0b\x32\x0e.V3PresetQuery\x12\x1e\n\x06query2\x18\x02 \x01(\x0b\x32\x0e.V3PresetQuery\"/\n\rV3PresetQuery\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\x05\x12\x0e\n\x06\x66ield2\x18\x02 \x01(\x05\"L\n\x17V3ResGetExposurePresets\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12#\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x15.V3ExposurePresetData\"E\n\x14V3ExposurePresetData\x12\x10\n\x08\x65xposure\x18\x01 \x01(\t\x12\x0c\n\x04gain\x18\x02 \x01(\x05\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\"7\n\x1bV3ReqSetObservationLocation\x12\x0b\n\x03lon\x18\x01 \x01(\x01\x12\x0b\n\x03lat\x18\x02 \x01(\x01\"\x19\n\x17V3ReqConfirmObservationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3_astro_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_V3REQSAVESTACKEDIMAGE']._serialized_start=18
  _globals['_V3REQSAVESTACKEDIMAGE']._serialized_end=55
  _globals['_V3RESSAVESTACKEDIMAGE']._serialized_start=57
  _globals['_V3RESSAVESTACKEDIMAGE']._serialized_end=108
  _globals['_V3REQLISTSAVEDIMAGES']._serialized_start=110
  _globals['_V3REQLISTSAVEDIMAGES']._serialized_end=132
  _globals['_V3REQSTATUSPOLLING']._serialized_start=134
  _globals['_V3REQSTATUSPOLLING']._serialized_end=218
  _globals['_V3REQGETASTROPARAMS']._serialized_start=220
  _globals['_V3REQGETASTROPARAMS']._serialized_end=255
  _globals['_V3RESGETASTROPARAMS']._serialized_start=257
  _globals['_V3RESGETASTROPARAMS']._serialized_end=328
  _globals['_V3ASTROPARAMSDATA']._serialized_start=330
  _globals['_V3ASTROPARAMSDATA']._serialized_end=446
  _globals['_V3REQSETASTROPARAMS']._serialized_start=448
  _globals['_V3REQSETASTROPARAMS']._serialized_end=485
  _globals['_V3RESSETASTROPARAMS']._serialized_start=487
  _globals['_V3RESSETASTROPARAMS']._serialized_end=543
  _globals['_V3REQGETEXPOSUREPRESETS']._serialized_start=545
  _globals['_V3REQGETEXPOSUREPRESETS']._serialized_end=633
  _globals['_V3PRESETQUERY']._serialized_start=635
  _globals['_V3PRESETQUERY']._serialized_end=682
  _globals['_V3RESGETEXPOSUREPRESETS']._serialized_start=684
  _globals['_V3RESGETEXPOSUREPRESETS']._serialized_end=760
  _globals['_V3EXPOSUREPRESETDATA']._serialized_start=762
  _globals['_V3EXPOSUREPRESETDATA']._serialized_end=831
  _globals['_V3REQSETOBSERVATIONLOCATION']._serialized_start=833
  _globals['_V3REQSETOBSERVATIONLOCATION']._serialized_end=888
  _globals['_V3REQCONFIRMOBSERVATION']._serialized_start=890
  _globals['_V3REQCONFIRMOBSERVATION']._serialized_end=915
# @@protoc_insertion_point(module_scope)
