# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v3_camera.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'v3_camera.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fv3_camera.proto\"%\n\x13V3ReqOpenTeleCamera\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\x05\"%\n\x13V3ReqOpenWideCamera\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3_camera_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_V3REQOPENTELECAMERA']._serialized_start=19
  _globals['_V3REQOPENTELECAMERA']._serialized_end=56
  _globals['_V3REQOPENWIDECAMERA']._serialized_start=58
  _globals['_V3REQOPENWIDECAMERA']._serialized_end=95
# @@protoc_insertion_point(module_scope)
