#!/usr/bin/env python3
"""Compare DwarfAlp command constants with the DWARFLAB APK registry."""

from __future__ import annotations

import argparse
import importlib
import json
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_APK_INVENTORY = ROOT / "docs" / "apk-analysis" / "api-inventory.json"


def _load_current_commands() -> list[dict[str, Any]]:
    sys.path.insert(0, str(ROOT / "src"))
    try:
        module = importlib.import_module("dwarf_alpaca.proto.protocol_pb2")
        return [
            {"name": value.name, "command_id": value.number}
            for value in module.DwarfCMD.DESCRIPTOR.values
        ]
    finally:
        sys.path.pop(0)


def _load_current_response_codes() -> list[dict[str, Any]]:
    sys.path.insert(0, str(ROOT / "src"))
    try:
        module = importlib.import_module("dwarf_alpaca.proto.protocol_pb2")
        return [
            {"name": value.name, "code": value.number}
            for value in module.DwarfErrorCode.DESCRIPTOR.values
        ]
    finally:
        sys.path.pop(0)


def _load_apk_commands(path: Path) -> list[dict[str, Any]]:
    return json.loads(path.read_text(encoding="utf-8"))["commands"]


def _source_usage() -> set[str]:
    names: set[str] = set()
    name_pattern = re.compile(r"(?:DwarfCMD|protocol_pb2\.DwarfCMD)\.(CMD_[A-Z0-9_]+)")
    for path in (ROOT / "src").rglob("*.py"):
        text = path.read_text(encoding="utf-8")
        names.update(name_pattern.findall(text))
    return names


def _compare(
    current: list[dict[str, Any]], apk: list[dict[str, Any]]
) -> dict[str, Any]:
    apk_by_name = {item["name"]: item for item in apk}
    apk_by_id: dict[int, list[dict[str, Any]]] = defaultdict(list)
    for item in apk:
        apk_by_id[item["command_id"]].append(item)
    used_names = _source_usage()
    exact_ids = {
        item["command_id"]
        for item in current
        if (same_name := apk_by_name.get(item["name"]))
        and same_name["command_id"] == item["command_id"]
    }
    records = []
    for item in current:
        name = item["name"]
        command_id = item["command_id"]
        same_name = apk_by_name.get(name)
        same_id = apk_by_id.get(command_id, [])
        if same_name and same_name["command_id"] == command_id:
            status = "CORRECT"
        elif same_name:
            status = "INCORRECT_ID"
        elif same_id and command_id in exact_ids:
            status = "DEPRECATED_ALIAS"
        elif same_id:
            status = "STALE_NAME"
        else:
            status = "UNKNOWN"
        records.append(
            {
                **item,
                "status": status,
                "used": name in used_names,
                "apk_same_name_id": same_name["command_id"] if same_name else None,
                "apk_names_at_id": [record["name"] for record in same_id],
            }
        )
    current_names = {item["name"] for item in current}
    apk_only = [item for item in apk if item["name"] not in current_names]
    return {"current": records, "apk_only": apk_only}


def _compare_response_codes(
    current: list[dict[str, Any]], apk: list[dict[str, Any]]
) -> dict[str, Any]:
    apk_by_name = {item["name"]: item for item in apk}
    apk_by_code: dict[int, list[dict[str, Any]]] = defaultdict(list)
    for item in apk:
        apk_by_code[item["code"]].append(item)
    exact_codes = {
        item["code"]
        for item in current
        if (same_name := apk_by_name.get(item["name"])) and same_name["code"] == item["code"]
    }
    records = []
    for item in current:
        same_name = apk_by_name.get(item["name"])
        same_code = apk_by_code.get(item["code"], [])
        if same_name and same_name["code"] == item["code"]:
            status = "CORRECT"
        elif same_name:
            status = "INCORRECT_VALUE"
        elif same_code and item["code"] in exact_codes:
            status = "DEPRECATED_ALIAS"
        else:
            status = "UNKNOWN"
        records.append(
            {
                **item,
                "status": status,
                "apk_same_name_code": same_name["code"] if same_name else None,
                "apk_names_at_code": [record["name"] for record in same_code],
            }
        )
    current_names = {item["name"] for item in current}
    return {
        "current": records,
        "apk_only": [item for item in apk if item["name"] not in current_names],
    }


def _markdown(report: dict[str, Any]) -> str:
    current = report["current"]
    counts: dict[str, int] = defaultdict(int)
    for item in current:
        counts[item["status"]] += 1
    lines = [
        "# Command registry comparison",
        "",
        "Generated by `tools/protocol/audit_commands.py` from the canonical `DwarfCMD` enum and the DWARFLAB APK 3.4.1 registry.",
        "",
        f"Current commands: **{len(current)}**. APK commands: **{len(report['apk_only']) + len({item['name'] for item in current if item['status'] in {'CORRECT', 'INCORRECT_ID'}})}**.",
        "",
        "Status counts: `" + json.dumps(dict(sorted(counts.items()))) + "`",
        "",
        "## Non-matching current entries",
        "",
        "| Current command | ID | Status | APK evidence at that ID | Referenced by name |",
        "|---|---:|---|---|---|",
    ]
    for item in current:
        if item["status"] == "CORRECT":
            continue
        alternatives = ", ".join(item["apk_names_at_id"]) or "none"
        if item["status"] == "INCORRECT_ID":
            alternatives += f"; same APK name is {item['apk_same_name_id']}"
        lines.append(
            f"| `{item['name']}` | {item['command_id']} | {item['status']} | `{alternatives}` | {'yes' if item['used'] else 'no'} |"
        )
    lines.extend(
        [
            "",
            "`DEPRECATED_ALIAS` retains source compatibility while the runtime uses the APK/firmware name. `STALE_NAME` means the numeric ID is registered by the APK under a different semantic name and is not automatically a safe rename.",
        ]
    )
    response_codes = report["response_codes"]["current"]
    response_counts: dict[str, int] = defaultdict(int)
    for item in response_codes:
        response_counts[item["status"]] += 1
    lines.extend(
        [
            "",
            "## Response/error codes",
            "",
            f"Current codes: **{len(response_codes)}**. APK codes: **{len(report['response_codes']['apk_only']) + sum(item['status'] in {'CORRECT', 'INCORRECT_VALUE'} for item in response_codes)}**.",
            "",
            "Status counts: `" + json.dumps(dict(sorted(response_counts.items()))) + "`",
            "",
            "| Current name | Code | Status | APK evidence at that code |",
            "|---|---:|---|---|",
        ]
    )
    nonmatching_codes = [item for item in response_codes if item["status"] != "CORRECT"]
    for item in nonmatching_codes:
        alternatives = ", ".join(item["apk_names_at_code"]) or "none"
        lines.append(
            f"| `{item['name']}` | {item['code']} | {item['status']} | `{alternatives}` |"
        )
    if not nonmatching_codes:
        lines.append("| _None_ | | | |")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--apk", type=Path, default=DEFAULT_APK_INVENTORY)
    parser.add_argument("--json", type=Path)
    parser.add_argument("--markdown", type=Path)
    args = parser.parse_args()
    apk_inventory = json.loads(args.apk.read_text(encoding="utf-8"))
    report = _compare(_load_current_commands(), apk_inventory["commands"])
    report["response_codes"] = _compare_response_codes(
        _load_current_response_codes(), apk_inventory["response_codes"]
    )
    if args.json:
        args.json.parent.mkdir(parents=True, exist_ok=True)
        args.json.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    if args.markdown:
        args.markdown.parent.mkdir(parents=True, exist_ok=True)
        args.markdown.write_text(_markdown(report), encoding="utf-8")
    if not args.json and not args.markdown:
        print(_markdown(report))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
